<?php

/**
 * Implements hook_uninstall().
 */
function og_menu_default_links_uninstall() {
  $bundles = og_get_all_group_bundle();
  $enable = FALSE;

  // Check if a setting exists
  if ($bundles) {
    foreach($bundles as $entity_type => $entity_bundles) {
      foreach ($entity_bundles as $bundle => $bundle_label) {
        $group_type = strtolower('_' . $bundle);
        $temp = variable_del('og_menu_default_links_' . $entity_type . $group_type, FALSE);
      }
    }
  }
}