<?php
/**
 * @file
 */

/**
 * Implements hook_theme().
 */
function views_fieldfilter_theme() {
  return array(
    'views_fieldfilter_admin_table' => array(
      'render element' => 'form',
      'file' => 'views_fieldfilter.theme.inc',
    ),
  );
}
/**
 * Implements hook_views_api().
 */
function views_fieldfilter_views_api() {
  return array(
    'api' => 3.0,
    'path' => drupal_get_path('module', 'views_fieldfilter') . '', 
    'template path' => drupal_get_path('module', 'views_fieldfilter') . '',
  );
}