<?php
/**
 * @file
 * Personalization for the contact form.
 */

/**
 * Implements hook_authcache_p13n_setting().
 */
function authcache_contact_authcache_p13n_setting() {
  return array(
    'authcache-contact' => array(
      'setting' => 'AuthcacheContactSetting',
      'setting target' => 'authcacheContact',
      'cache maxage' => 86400,
    ),
  );
}

/**
 * Implements hook_authcache_p13n_admin_config().
 */
function authcache_contact_authcache_p13n_admin_config() {
  $configs = array();

  $config = array(
    'lifespan' => 86400,
  );

  $configs[] = array(
    'title' => t('User name and e-mail address'),
    'group' => t('Contact'),
    'type' => 'settings',
    'id' => 'authcache-contact',
    'location' => t('Contact form'),
    'config' => $config + authcache_p13n_config_defaults(),
  );

  return $configs;
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Remove default values on contact form.
 */
function authcache_contact_form_contact_site_form_alter(&$form, &$form_state) {
  if (user_is_logged_in() && authcache_page_is_cacheable()) {
    unset($form['name']['#default_value']);
    unset($form['mail']['#default_value']);

    $p13n_setting = array(
      '#setting' => 'authcache-contact',
      '#attached' => array(
        'js' => array(drupal_get_path('module', 'authcache_contact') . '/authcache_contact.js'),
      ),
    );
    $form['#attached']['authcache_p13n_add_setting'][] = array($p13n_setting);
  }
}
